name: Sphinx Build in CI

on:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Clone connect-tools
        uses: actions/checkout@v2
        with:
          repository: owkin/connect-tools
          token: ${{ secrets.ACCESS_TOKEN }}
          path: connect-tools

      - name: Clone substra
        uses: actions/checkout@v2
        with:
          repository: owkin/substra
          token: ${{ secrets.ACCESS_TOKEN }}
          path: substra

      - name: Clone substrafl
        uses: actions/checkout@v2
        with:
          repository: owkin/connectlib
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: main
          path: substrafl

      - name: Install substra, connect-tools and substrafl
        run: |
          pip install -e ./substra
          pip install -e ./connect-tools
          pip install -e './substrafl[dev]'

      - name: Copy substra and substrafl api doc in the doc
        run: |
          cp -r substra/references docs/source/documentation/references
          cp -r substrafl/docs/api docs/source/substrafl_doc/

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Sphinx make
        working-directory: ./docs
        run: make clean html
