name: Sphinx Build in CI

on:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Checkout pyconfig from a private repos
        uses: actions/checkout@v2
        with:
          repository: owkin/substra
          token: ${{ secrets.ACCESS_TOKEN }}
          path: substra

      - name: Install package
        run: |
             pip install -e substra

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Sphinx make
        working-directory: ./docs
        run: make clean && make html

      # exchange the absolute path given by sphinx-gallery with relative path
      - name: replace absolute paths
        run: sed -i "s+//home/runner/work/connect-documentation/connect-documentation/docs/source/auto_examples/++g;" docs/source/auto_examples/index.rst

      # uploads artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: build-for-${{ github.sha }}
          path: docs/source/
