name: Sphinx Build and RTD publish for latest

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # Pattern matched against refs/tags

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Clone connect-tools
        uses: actions/checkout@v2
        with:
          repository: owkin/connect-tools
          token: ${{ secrets.ACCESS_TOKEN }}
          path: connect-tools

      - name: Clone substra
        uses: actions/checkout@v2
        with:
          repository: owkin/substra
          token: ${{ secrets.ACCESS_TOKEN }}
          path: substra

      - name: Clone connectlib
        uses: actions/checkout@v2
        with:
          repository: owkin/connectlib
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: main
          path: connectlib

      - name: Install substra, connect-tools and connectlib
        run: |
          pip install -e substra
          pip install -e connect-tools
          pip install -e connectlib[dev]

      - name: Copy substra and connectlib api doc in the doc
        run: |
          cp -r substra/references docs/source/documentation/references
          cp -r connectlib/docs/api docs/source/connectlib/  

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Sphinx make
        working-directory: ./docs
        run: make clean && make html

      # exchange the absolute path given by sphinx-gallery with relative path
      - name: replace absolute paths
        run: sed -i "s+//home/runner/work/connect-documentation/connect-documentation/docs/source/auto_examples/++g;" docs/source/auto_examples/index.rst

      - uses: actions/upload-artifact@v2
        with:
          name: build-for-${{ github.sha }}
          path: docs/source/

      - name: Trigger RTDs build
        # TODO: for now using personal repo because of changes which needed to be applied
        # to the action so it works on private repos. Once the original one is published it should be updated to:
        # dfm/rtds-action  -> commit of interest 66a4e12
        uses: maikia/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
